@extends('panel.client.layout.app')
@section('content')
<main class="cp-main cp-services">
 <section class="cp-products__header"><div><p class="cp-eyebrow cp-eyebrow--dark"><span></span> Website content</p><h1>Blogs</h1><p>Publish articles with images and complete content.</p></div><button class="cp-add-product" id="blog-open" type="button"><span>+</span> Add blog</button></section>
 @forelse($blogs as $blog)
 @if($loop->first)<section class="cp-service-grid">@endif
 <article class="cp-service-card">@if($blog->featured_image)<img src="/{{ ltrim($blog->featured_image,'/') }}" alt="{{ $blog->title }}">@else<div class="cp-service-card__placeholder">&#9998;</div>@endif<div class="cp-service-card__body"><span class="cp-service-card__position">{{ $blog->status }} · {{ $blog->publish_date?->format('d M Y') ?? 'No date' }}</span><h2>{{ $blog->title }}</h2><p>{{ $blog->excerpt ?: Str::limit($blog->content,115) }}</p><div class="cp-service-card__actions"><button class="blog-edit" data-id="{{ $blog->id }}" data-title="{{ $blog->title }}" data-excerpt="{{ $blog->excerpt }}" data-content="{{ $blog->content }}" data-date="{{ optional($blog->publish_date)->format('Y-m-d') }}" data-status="{{ $blog->status }}" data-meta-title="{{ $blog->meta_title }}" data-meta-description="{{ $blog->meta_description }}">Edit</button><button class="delete-btn" data-id="{{ $blog->id }}" data-url="{{ route('panel.client-blogs.delete',$blog->id) }}">Delete</button></div></div></article>
 @if($loop->last)</section>@endif
 @empty <section class="cp-gallery-empty"><span>&#9998;</span><h2>No blog posts</h2><p>Write your first article for the website.</p><button class="cp-add-product" id="blog-empty" type="button"><span>+</span> Add blog</button></section>
 @endforelse
 @if($blogs->hasPages())<div class="cp-gallery-pagination">{{ $blogs->links('pagination::tailwind') }}</div>@endif
</main>
<div class="service-modal" id="blog-modal" aria-hidden="true"><div class="service-modal__backdrop" data-blog-close></div><section class="service-modal__dialog"><header><div><p class="cp-eyebrow cp-eyebrow--dark"><span></span> Website blog</p><h2 id="blog-title">Add blog</h2></div><button type="button" class="ws-modal__close" data-blog-close>&times;</button></header><form id="blog-form" action="{{ route('panel.client-blogs.store') }}" method="POST" enctype="multipart/form-data">@csrf<div class="ws-grid"><label>Title<input name="title" required></label><label>Publish date<input type="date" name="publish_date"></label><label>Status<select name="status"><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Featured image<input id="blog-image" type="file" name="featured_image" accept=".jpg,.jpeg,.png,.webp" required></label><label class="ws-span-2">Excerpt<input name="excerpt" maxlength="500"></label><label class="ws-span-2">Full content<textarea name="content" rows="6"></textarea></label><label class="ws-span-2">SEO title<input name="meta_title"></label><label class="ws-span-2">SEO description<textarea name="meta_description" rows="3"></textarea></label></div><footer><button class="cp-add-product" type="submit">Save blog</button></footer></form></section></div>
<script>document.addEventListener('DOMContentLoaded',function(){var m=document.getElementById('blog-modal'),f=document.getElementById('blog-form'),i=document.getElementById('blog-image');function o(b){f.reset();f.action="{{ route('panel.client-blogs.store') }}";i.required=true;document.getElementById('blog-title').textContent='Add blog';if(b){f.action="{{ url('/panel/user/blogs') }}/"+b.dataset.id;['title','excerpt','content','date','status','metaTitle','metaDescription'].forEach(function(k){var n=k==='date'?'publish_date':k.replace(/[A-Z]/g,function(x){return '_'+x.toLowerCase()});f.elements[n].value=b.dataset[k]||''});i.required=false;document.getElementById('blog-title').textContent='Edit blog'}m.classList.add('is-open')}function c(){m.classList.remove('is-open')}['blog-open','blog-empty'].forEach(function(id){var b=document.getElementById(id);if(b)b.onclick=function(){o()}});document.querySelectorAll('.blog-edit').forEach(function(b){b.onclick=function(){o(b)}});m.querySelectorAll('[data-blog-close]').forEach(function(b){b.onclick=c})});</script>
@endsection